remote_theme: xindong/jekyll-theme-primer
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

exclude:
  - node_modules
  - script

sass:
  style: :compressed

theme: jekyll-theme-primer

markdown: kramdown
kramdown:
  parse_block_html: true
  
github:
  private: false
  license:
    name: MIT
  source:
    branch: "master"
    path: "/"
  repository_url: "https://github.com/pages-themes/primer"
  
title:  Tianli Xia
description: UW-Madison Economics Ph.D. student 
